### ISSUE TITLE
샵 정보 - 직원 정보 수정, 스타일 정보 수정 UI 개발

### ISSUE THREAD

**Issue by raaang** [raaang/BeautySalonCRM#22]
## Content
샵 정보
- 직원 정보 수정 화면 UI 개발
- 스타일 정보 수정 화면 UI 개발

## Todo List
- [x] 직원 정보 수정 화면 UI 개발
- [x] 스타일 정보 수정 화면 UI 개발
- [x] calendar library 선택 후 적용

## Etc
calendar library

**Comment by raaang** [comment]
[MS] Feat: 샵 정보 수정 UI 구현, 샵 스타일 정보 수정 UI 구현 - #37
