### ISSUE TITLE
개발 규칙 수립

### ISSUE THREAD

**Issue by joo-ju** [raaang/BeautySalonCRM#24]
## Content
협업 시 필요한 각종 개발 규칙들을 정함

## Todo List
**공통**
- [x] 브랜치명 통일 (MS-21 확정)
(MS-21 or MS-#21)

**Backend**
- [ ] 쿼리 정렬 방법(ex. ANSI)
- [ ] 파일명 대문자로 시작 (ex. CustomerSave.xml)
- [ ] 쿼리 전체 대문자
- [ ] 테이블 정의 쿼리 디스코드에 업로드(칼럼별 주석 포함)
