### ISSUE TITLE
샵 정보 - 샵 등록 (회원가입/로그인) UI 개발

### ISSUE THREAD

**Issue by cloud0406** [raaang/BeautySalonCRM#3]
## Content
샵 정보 - 샵 등록 (회원가입/로그인) UI 개발

## Todo List
- [x] 샵 등록 회원가입 화면 UI 개발 
- [x] 샵 등록 로그인 화면 UI 개발 
- [x] input 컴포넌트 개발
- [x] select 컴포넌트 개발
- [x] text 컴포넌트 개발
- [x] modal 컴포넌트 개발
- [x] input container 컴포넌트 개발

**Comment by raaang** [comment]
개발 완료
