### ISSUE TITLE
고객관리 - 회원 상세 정보 페이지 UI 개발

### ISSUE THREAD

**Issue by cloud0406** [raaang/BeautySalonCRM#31]
## Content
고객관리 - 회원 상세 정보 페이지의 전체 UI를 개발

## Todo List
- [x] 회원 상세 정보 페이지 컴포넌트
- [x] #34
- [x] #35
   - [ ] 결제하기 모달
   - [ ] 예약시 예약 페이지로 이동
   - [x] 내역 컴포넌트
- [x] #36
- [x] #38
   - [ ] 내역 list 컴포넌트 
   - [ ] 내역 컴포넌트

## Etc
docs, reference, library 등 개발에 필요한 내용 작성
논의할 내용 작성

**Comment by cloud0406** [comment]
완료
