### ISSUE TITLE
샵 정보 - 메인화면 UI 개발

### ISSUE THREAD

**Issue by cloud0406** [raaang/BeautySalonCRM#4]
## Content
샵 정보 메인화면 UI 개발

## Todo List
- [x] infoContainer 만들기
- [x] table 컴포넌트 만들기
- [x] 데이터 list 처리
- [x] 페이지네이션 컴포넌트 만들기
- [x] #14

**Comment by cloud0406** [comment]
완료
