### ISSUE TITLE
결제 모달 UI 상황별로 수정

### ISSUE THREAD

**Issue by cloud0406** [raaang/BeautySalonCRM#87]
## Content
결제모달이 예약건 결제, 미예약건 결제, 결제 내역 수정 등 상황에 맞는 UI를 보여주도록 수정

## Todo List
- [x] 예약건일경우 '예약시간', '예약자' 추가로 보여주기
    - [x] 담당자, 요청사항, 예약시간, 예약자, 스타일 예약 데이터 기본 값으로 보여주기
- [x] 수정건일경우 결제날짜~스타일까지 disabled 처리

## Etc
docs, reference, library 등 개발에 필요한 내용 작성
논의할 내용 작성
