### ISSUE TITLE
고객관리 - 회원등록, 검색 페이지 UI 개발

### ISSUE THREAD

**Issue by raaang** [raaang/BeautySalonCRM#89]
## Content
회원등록, 검색 페이지 전체 UI 개발

## Todo List
- [ ] 회원 등록 화면 UI 개발
- [ ] 회원 검색 화면 UI 개발
	- [ ] 회원 검색 필터 선택 컴포넌트
		- [ ] 담당자 검색 모달 컴포넌트
	- [ ] 검색 결과 테이블 컴포넌트
